---
- name: "copy {{ aws_cwa_config_name }} configuration"
  become: yes
  become_method: sudo
  template:
    dest: "{{ aws_cwa_dest_path }}/etc/{{ aws_cwa_config_name }}.json"
    src: templates/cwa_config.json.j2
    mode: "0644"
  notify: restart amazon-cwa
  tags:
    - cloudwatch-agent_config
  