---
- name: "Copy {{ aws_cwa_config_name }} config file then restart the agent"
  become: yes
  become_method: sudo
  template:
    dest: "{{ aws_cwa_dest_path }}/etc/{{ aws_cwa_config_name }}.json"
    src: templates/cwa_config.json.j2
    mode: "0644"
  tags:
    - cloudwatch-agent_config
  notify: restart amazon-cwa
 