---
- name: restart amazon-cwa
  command: |
      amazon-cloudwatch-agent-ctl \
        -a append-config \
        -m ec2 \
        -c "ssm:{{ aws_cwa_config_name }}" \
        -s
  args:
      chdir: "{{ aws_cwa_dest_path }}/bin"
  become_method: sudo
  become: true
